[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
build = "build.rs"
name = "mdbook-epub"
version = "0.1.0"

[build-dependencies]
cargo = "0.23.0"

[dependencies]
epub-builder = "0.3.0"
failure = "0.1.1"
failure_derive = "0.1.1"
pulldown-cmark = "0.1.0"
semver = "0.9.0"
serde_json = "1.0.8"

[dependencies.mdbook]
branch = "alternate_backends"
git = "https://github.com/Michael-F-Bryan/mdbook"
[patch.crates-io.pulldown-cmark]
git = "https://github.com/google/pulldown-cmark"
